title: Hello World
views:
  - title: View 1
    path: view1
    cards:
      - type: entities
        entities:
          - light.kitchen_ceiling_light_1
          - light.kitchen_ceiling_light_2
  - title: View 2
    path: view2
    cards:
      - type: entities
        entities:
          - light.kitchen_ceiling_light_1
          - light.kitchen_ceiling_light_2
          - test